### ISSUE TITLE
Authenticating user - 401 response 

### ISSUE THREAD

**Issue by Hanked** [auth0-blog/hapi-jwt-authentication#3]
Hi, great tutorial and boilerplate API, really helpful.

**Steps to reproduce**
Make a successful `/api/users` POST request:

<img width="758" alt="screen shot 2016-05-10 at 02 13 22" src="https://cloud.githubusercontent.com/assets/9929871/15132790/ee509024-1654-11e6-87a1-a9e2759bc0ac.png">

Then attempt a `/api/users/authenticate` POST request using the same credentials:

<img width="765" alt="screen shot 2016-05-10 at 02 17 59" src="https://cloud.githubusercontent.com/assets/9929871/15132856/7b10718c-1655-11e6-88d6-a24c638d0c02.png">

Not sure whether my authenticate request is wrong or there is a bug in the API. Would really appreciate some help. I would love to start a project based on this repo.

Cheers!

**Comment by chenkie** [comment]
I've put in `auth: false` to that endpoint. Let me know if it works now :)
