### ISSUE TITLE
bcrypt dependency replacement

### ISSUE THREAD

**Issue by celliott181** [auth0-blog/hapi-jwt-authentication#6]
I'm wondering if it would be advisable to replace the dependency on bcrypt with a dependency on [bcryptjs](https://www.npmjs.com/package/bcryptjs). The original bcrypt has a very intricate set of installation dependencies when running under Windows thanks to its dependence on node-gyp. This led to npm errors that are way out of the scope of the tutorial, and bcryptjs is considered a drop in replacement when it comes to compatibility.

**Comment by chenkie** [comment]
If it's a drop-in replacement and works well with Windows then I'm all for it :) PRs welcome.
